name: New Release (v2)
run-name: Release v${{ github.event.inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version number"
        required: true
        default: "0.0.0"
      binary_build:
        description: "Build binaries"
        required: true
        default: "true"
        type: choice
        options:
          - true
          - false
      is_latest:
        description: "Set as latest"
        required: true
        default: "false"
        type: choice
        options:
          - true
          - false

env:
  PIP_USE_PEP517: true

jobs:
  build-client:
    runs-on: ubuntu-latest
    name: Build client
    steps:
      - name: Clone client
        uses: actions/checkout@v4
        with:
          repository: "swingmx/webclient"
          path: swingmusic-client

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Install dependencies & Build client
        run: |
          cd swingmusic-client
          yarn install
          yarn build --outDir ../client
          cd ..

      - name: Upload client
        uses: actions/upload-artifact@v4
        with:
          path: "client/"
          compression-level: 0
          name: "client"

  build-wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    needs: [build-client]

    steps:
      - name: Checkout swingmusic
        uses: actions/checkout@v4
        with:
          repository: 'swingmx/swingmusic'
          ref: v${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: client
          path: client

      - name: Compress client and copy to src/swingmusic/client.zip
        run: |
          zip -r client.zip client
          rm -r client
          cp client.zip src/swingmusic/client.zip

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build wheels
        run: pip wheel . -w wheelhouse --no-deps

      - uses: actions/upload-artifact@v4
        with:
          # name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          compression-level: 0
          name: "wheels"


  build-pyinstaller:
    name: Build binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [build-client, build-wheels]
    if: ${{ github.event.inputs.binary_build == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-22.04-arm,
          ]

    steps:
      - name: Checkout swingmusic
        uses: actions/checkout@v4
        with:
          repository: 'swingmx/swingmusic'
          ref: v${{ github.event.inputs.tag }}
          sparse-checkout: |
            swingmusic.spec
            src/swingmusic/assets

      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: client
          path: client

      - name: Compress client (Unix)
        if: runner.os != 'Windows'
        run: |
          zip -r client.zip client

      - name: Compress client (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path client -DestinationPath client.zip -Force

      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: wheels
          merge-multiple: true

      # install system packages
      - name: Setup Homebrew
        if: ${{ startsWith(matrix.os, 'macos') }}
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install libev (macOS)
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          brew install libev

      - name: Install libev (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get install libev-dev -y > /dev/null

      - name: Install swingmusic
        run: |
          pip install --find-links=wheels/ swingmusic[build]

      - name: Build with Pyinstaller on ${{ matrix.os }}
        run: pyinstaller swingmusic.spec

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pyinstaller-${{ matrix.os }}
          path: ./dist/swingmusic_*
          compression-level: 0

  upload-builds:
    name: Uploading builds to release
    runs-on: ubuntu-latest
    needs: [build-client, build-wheels, build-pyinstaller]

    steps:
      - name: Checkout swingmusic
        uses: actions/checkout@v4
        with:
          repository: 'swingmx/swingmusic'
          ref: v${{ github.event.inputs.tag }}
          sparse-checkout: |
            .github/changelog.md

      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: client
          path: client

      - name: compress client
        run: |
          zip -r client.zip client
          rm -r client

      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: wheels
          merge-multiple: true

      - name: Download all Pyinstaller builds
        uses: actions/download-artifact@v4
        with:
          pattern: Pyinstaller-*
          path: pyinstaller
          merge-multiple: true

      - name: Upload artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          name: ${{ format('v{0}',github.event.inputs.tag) }}
          tag: ${{ format('v{0}',github.event.inputs.tag) }}
          bodyFile: .github/changelog.md
          artifactErrorsFailBuild: true
          commit: ${{ github.sha }}
          makeLatest: ${{github.event.inputs.is_latest == 'true'}}
          artifacts: "client.zip,wheels/*,pyinstaller/*"
          token: ${{ secrets.PAT }}
