name: New Release (v2)
run-name: Release v${{ github.event.inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version number"
        required: true
        default: "0.0.0"
      binary_build:
        description: "Build binaries"
        required: true
        default: "true"
        type: choice
        options:
          - true
          - false
      is_latest:
        description: "Set as latest"
        required: true
        default: "false"
        type: choice
        options:
          - true
          - false

env:
  PIP_USE_PEP517: true

jobs:
  build-pyinstaller:
    name: Build binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.inputs.binary_build == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-22.04-arm,
          ]

    steps:
      - name: Checkout swingmusic
        uses: actions/checkout@v4
        with:
          repository: 'swingmx/swingmusic'
          ref: v${{ github.event.inputs.tag }}
          sparse-checkout: |
            swingmusic.spec
            src/swingmusic/assets

      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Download client artifact
        uses: robinraju/release-downloader@v1
        with:
          repository: 'swingmx/swingmusic'
          tag: v${{ github.event.inputs.tag }}
          fileName: 'swingmusic-${{ github.event.inputs.tag }}-py3-none-any.whl'
          out-file-path: wheels

      - name: Download wheels artifact
        uses: robinraju/release-downloader@v1
        with:
          repository: 'swingmx/swingmusic'
          tag: v${{ github.event.inputs.tag }}
          fileName: 'client.zip'

      # install system packages
      - name: Install libev (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get install libev-dev -y > /dev/null

      - name: Install swingmusic
        run: |
          pip install --find-links=wheels/ swingmusic[build]

      - name: Build with Pyinstaller on ${{ matrix.os }}
        run: pyinstaller swingmusic.spec

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pyinstaller-${{ matrix.os }}
          path: ./dist/swingmusic_*
          compression-level: 0

  upload-builds:
    name: Uploading builds to release
    runs-on: ubuntu-latest
    needs: [build-pyinstaller]

    steps:
      - name: Checkout swingmusic
        uses: actions/checkout@v4
        with:
          repository: 'swingmx/swingmusic'
          ref: v${{ github.event.inputs.tag }}
          sparse-checkout: |
            .github/changelog.md

      - name: Download all Pyinstaller builds
        uses: actions/download-artifact@v4
        with:
          pattern: Pyinstaller-*
          path: pyinstaller
          merge-multiple: true

      - name: Upload artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          name: ${{ format('v{0}',github.event.inputs.tag) }}
          tag: ${{ format('v{0}',github.event.inputs.tag) }}
          bodyFile: .github/changelog.md
          artifactErrorsFailBuild: true
          commit: ${{ github.sha }}
          makeLatest: ${{github.event.inputs.is_latest == 'true'}}
          artifacts: "pyinstaller/*"
          token: ${{ secrets.GITHUB_TOKEN }}
